version: '3.8'

networks:
  process:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1

services:
  process_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: process_app
    restart: always
    ports:
      - "${SPRING_BOOT_PORT:-9098}:9098"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://localhost:5432/etl_job}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-nabeel.amd93}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-admin}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
      EFS_FILE_DIRE: ${EFS_FILE_DIRE:-/tmp/efs}
      TOPIC_TEST: ${TOPIC_TEST:-test-topic}
      TOPIC_TRUCK: ${TOPIC_TRUCK:-truck-topic}
      TOPIC_SCRAP: ${TOPIC_SCRAP:-scrapping-topic}
      MAIL_HOST: ${MAIL_HOST:-sandbox.smtp.mailtrap.io}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-ce545af2135fd6}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-35f35312703886}
      SOCKET_SESSION_ID: ${SOCKET_SESSION_ID:-0hw0dz34}
      SOCKET_TRANSACTION_ID: ${SOCKET_TRANSACTION_ID:-40ef-dd1d-bd9f-1d7f}
    volumes:
      - ./logs:/app/logs
      - /tmp/efs:/tmp/efs
    networks:
      - process
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9098/api/v1/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
